project:
  type: website
  output-dir: docs

website:
  title: "Introduction to R for Data Analysis"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Set up"
        href: setup.html
      - text: "1. Introduction to R & RStudio"
        href: 01_rstudio.html
      - text: "2. Creating plots"
        href: 02_ggplot.html
      - text: "3. R data types"
        href: 03_explore.html
      - text: "4. Manipulating data"
        href: 04_dplyr.html
      - text: "Resources"
        href: resources.html