---
title: "Setup"
---

# 1. Install R & RStudio

### On a device managed by your organisation:

- Install R and then RStudio from your organisation's software repository (or contact your IT department for help).

### On a personal device:

- Install [R](https://cran.stat.auckland.ac.nz/) and then [RStudio](https://posit.co/download/rstudio-desktop/) directly.

# 2. Install required R package

- Open RStudio, click on Tools -> Install Packages.
- Type `tidyverse` and click install.
- Wait for the background process to finish (can take a couple of minutes).

# 3. Know how to check for updates

- Keep R up to date by checking your organisation's software repository or CRAN every now and then.
- Keep RStudio up to date by checking your organisation's software repository, or on personal devices by following the update prompts in outdated versions.
- Keep packages up to date by clicking Tools > 'Check for package updates' every now and then.

# 4. Download the data

- Download the [data file](data_raw/surveys_complete.csv) and save it somewhere convenient for now.